# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_point',
            fields=[
                ('access_point_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='アクセスポイントID')),
                ('raspberry_pi_number', models.CharField(max_length=6, verbose_name='RaspberryPi識別番号')),
                ('access_point_name', models.TextField(max_length=50, verbose_name='アクセスポイント名')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='キャラクターID')),
                ('character_name', models.CharField(max_length=20, verbose_name='キャラクター名')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Character_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_condition', models.CharField(max_length=2, verbose_name='天気条件')),
                ('character_file_pass', models.TextField(max_length=50, verbose_name='キャラクターファイルパス')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
                ('access_point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Access_point')),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('coordinate_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='座標ID')),
                ('place_name', models.TextField(max_length=50, verbose_name='地名')),
                ('latitude', models.FloatField(max_length=10, verbose_name='緯度')),
                ('longitude', models.FloatField(max_length=11, verbose_name='経度')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('environment_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='環境ID')),
                ('weather', models.CharField(max_length=10, verbose_name='天気')),
                ('temperature', models.CharField(max_length=5, verbose_name='気温')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='メッセージID')),
                ('text_data', models.TextField(verbose_name='テキストデータ')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_path',
            fields=[
                ('photo_path_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='写真ファイルパスID')),
                ('photo_file_path', models.TextField(max_length=50, verbose_name='写真ファイルパス')),
                ('photo_index', models.IntegerField(max_length=2, verbose_name='写真索引番号')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Point_temperature',
            fields=[
                ('point_temperature_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='局所気温ID')),
                ('point_temperature', models.FloatField(max_length=5, verbose_name='局所気温')),
                ('acquisition_rank', models.IntegerField(max_length=2, verbose_name='取得順位')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
                ('access_point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Access_point')),
                ('environment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='観光地ID')),
                ('spot_name', models.TextField(max_length=50, verbose_name='観光地名')),
                ('spot_phoname', models.TextField(max_length=50, verbose_name='フリガナ')),
                ('steet_address', models.TextField(max_length=50, verbose_name='住所')),
                ('postal_code', models.IntegerField(verbose_name='郵便番号')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
                ('coordinate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Coordinate')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Spot_photo',
            fields=[
                ('spot_photo_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='写真グループID')),
                ('photo_number', models.IntegerField(verbose_name='写真枚数')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Spot')),
                ('use_photo_path_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Photo_path')),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Spot'),
        ),
        migrations.AddField(
            model_name='character_data',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Message'),
        ),
        migrations.AddField(
            model_name='access_point',
            name='coordinate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Coordinate'),
        ),
        migrations.AddField(
            model_name='access_point',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Spot'),
        ),
    ]
