# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='steet_address',
            new_name='street_address',
        ),
    ]
