# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20171227_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character_data',
            name='message_id',
        ),
        migrations.AddField(
            model_name='access_point',
            name='message_id',
            field=models.ForeignKey(default='me0001', on_delete=django.db.models.deletion.CASCADE, to='cms.Message'),
            preserve_default=False,
        ),
    ]
