# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20171228_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character_data',
            name='id',
        ),
        migrations.AddField(
            model_name='character_data',
            name='character_data_id',
            field=models.CharField(default='cd0001', max_length=6, primary_key=True, serialize=False, verbose_name='キャラクターデータID'),
            preserve_default=False,
        ),
    ]
