# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20171228_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_data',
            name='weather_condition',
            field=models.CharField(choices=[('晴天', '晴天'), ('雨天', '雨天')], max_length=2, verbose_name='天気条件'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='temperature',
            field=models.CharField(max_length=5, null=True, verbose_name='気温'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='weather',
            field=models.CharField(choices=[('晴れ', '晴れ'), ('曇り', '曇り'), ('雨', '雨'), ('雪', '雪'), ('雷雲', '雷雲'), ('霧雨', '霧雨'), ('霧', '霧')], max_length=10, null=True, verbose_name='天気'),
        ),
    ]
