# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180106_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='temperature',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='気温'),
        ),
    ]
