# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20180106_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='weather',
            field=models.CharField(blank=True, choices=[('晴れ', '晴れ'), ('曇り', '曇り'), ('雨', '雨'), ('雪', '雪'), ('雷雲', '雷雲'), ('霧雨', '霧雨'), ('霧', '霧')], max_length=10, null=True, verbose_name='天気'),
        ),
    ]
