# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20180106_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_path',
            name='photo_index',
        ),
        migrations.AlterField(
            model_name='environment',
            name='weather',
            field=models.CharField(blank=True, choices=[('晴れ', '晴れ'), ('曇り', '曇り'), ('雨', '雨'), ('雪', '雪'), ('雷雲', '雷雲'), ('霧雨', '霧雨'), ('霧', '霧'), ('その他', 'その他')], max_length=10, null=True, verbose_name='天気'),
        ),
        migrations.AlterField(
            model_name='point_temperature',
            name='acquisition_rank',
            field=models.IntegerField(verbose_name='取得順位'),
        ),
    ]
