# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20180113_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='coordinate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Coordinate', verbose_name='座標ID'),
        ),
    ]
