# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20180113_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Spot', verbose_name='環境ID'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Message', verbose_name='メッセージID'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='postal_code',
            field=models.IntegerField(max_length=7, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='spot_photo',
            name='photo_number',
            field=models.IntegerField(max_length=2, verbose_name='写真枚数'),
        ),
        migrations.AlterField(
            model_name='spot_photo',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Spot', verbose_name='観光地ID'),
        ),
        migrations.AlterField(
            model_name='spot_photo',
            name='use_photo_path_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Photo_path', verbose_name='使用写真パスID'),
        ),
    ]
