# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 03:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20180113_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1111111), django.core.validators.MaxValueValidator(9999999)], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='spot_photo',
            name='photo_number',
            field=models.IntegerField(verbose_name='写真枚数'),
        ),
    ]
