# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 03:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20180113_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)], verbose_name='郵便番号'),
        ),
    ]
