# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 03:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20180113_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='郵便番号'),
        ),
    ]
