# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 04:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20180113_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_point',
            name='coordinate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Coordinate', verbose_name='座標ID'),
        ),
        migrations.AlterField(
            model_name='access_point',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Message', verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='access_point',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Spot', verbose_name='観光地ID'),
        ),
        migrations.AlterField(
            model_name='character_data',
            name='access_point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Access_point', verbose_name='アクセスポイントID'),
        ),
        migrations.AlterField(
            model_name='character_data',
            name='character_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Character', verbose_name='キャラクターID'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Spot', verbose_name='観光地ID'),
        ),
        migrations.AlterField(
            model_name='point_temperature',
            name='access_point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Access_point', verbose_name='アクセスポイントID'),
        ),
        migrations.AlterField(
            model_name='point_temperature',
            name='acquisition_rank',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='取得順位'),
        ),
        migrations.AlterField(
            model_name='point_temperature',
            name='environment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Environment', verbose_name='環境ID'),
        ),
        migrations.AlterField(
            model_name='spot_photo',
            name='photo_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='写真枚数'),
        ),
    ]
