# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 04:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20180113_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_point',
            name='access_point_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='アクセスポイントID'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='キャラクターID'),
        ),
        migrations.AlterField(
            model_name='character_data',
            name='character_data_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='キャラクターデータID'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='coordinate_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='座標ID'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='environment_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='環境ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='メッセージID'),
        ),
        migrations.AlterField(
            model_name='photo_path',
            name='photo_path_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='写真ファイルパスID'),
        ),
        migrations.AlterField(
            model_name='point_temperature',
            name='point_temperature_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='局所気温ID'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='観光地ID'),
        ),
        migrations.AlterField(
            model_name='spot_photo',
            name='spot_photo_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='写真グループID'),
        ),
    ]
